# Generated by Django 5.1.15 on 2026-05-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
