# Generated by Django 5.2.14 on 2026-05-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_address_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='for_sensor',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
