# Generated by Django 5.2.14 on 2026-06-26 22:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm_hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizationRecommendationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('crop_id', models.CharField(blank=True, default='', max_length=255)),
                ('growth_stage', models.CharField(blank=True, default='', max_length=255)),
                ('task_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('in_progress', 'در حال مصرف'), ('pending_confirmation', 'منتظر تایید'), ('completed', 'پایان یافته')], db_index=True, default='pending_confirmation', max_length=64)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizations', to='farm_hub.farmhub')),
            ],
            options={
                'db_table': 'fertilization_requests',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FertilizationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('source', models.CharField(choices=[('recommendation', 'توصیه هوش مصنوعی'), ('free_text', 'متن آزاد کاربر')], db_index=True, max_length=32)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('crop_id', models.CharField(blank=True, default='', max_length=255)),
                ('growth_stage', models.CharField(blank=True, default='', max_length=255)),
                ('plan_payload', models.JSONField(blank=True, default=dict)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilization_plans', to='farm_hub.farmhub')),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='fertilization_recommendation.fertilizationrecommendationrequest')),
            ],
            options={
                'db_table': 'fertilization_plans',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
