# Generated by Django 5.2.14 on 2026-07-03 13:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisioningTask',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('farm_id', models.PositiveIntegerField(blank=True, null=True)),
                ('task_type', models.CharField(choices=[('subscription', 'Subscription'), ('device', 'Device')], max_length=21)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Proccesing'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provisioning_tasks', to='order.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provisioning_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
