# Generated by Django 5.2.14 on 2026-07-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisioningtask',
            name='item',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
