# Generated by Django 5.2.14 on 2026-07-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0002_provisioningtask_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provisioningtask',
            name='task_type',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('installation_service', 'Installation Service'), ('device', 'Device')], max_length=21),
        ),
    ]
