# Generated by Django 5.2.14 on 2026-06-14 21:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('symbol', models.CharField(max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1.0, max_digits=18)),
                ('is_base', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('fixed', 'fixed_price'), ('percentage', 'percentage')], default='fixed', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('usage_limit', models.PositiveIntegerField(default=0)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BasePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='base_prices', to='commerce_catalog.sku')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_prices', to='pricing.currency')),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_type', models.CharField(choices=[('base', 'base_price'), ('tier', 'tier_price')], default='base', max_length=10)),
                ('old_price', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('new_price', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='pricing.currency')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='commerce_catalog.sku')),
            ],
        ),
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('min_quantity', models.PositiveIntegerField(default=1)),
                ('max_quantity', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tier', to='pricing.currency')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tier', to='commerce_catalog.sku')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountSellableItemRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellable_item_relation', to='pricing.discountprice')),
                ('sellable_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_relation', to='commerce_catalog.sellableitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('discount', 'sellable_item'), name='unique_discount_sellable_item')],
            },
        ),
        migrations.CreateModel(
            name='DiscountSKURelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_relation', to='pricing.discountprice')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_relation', to='commerce_catalog.sku')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('discount', 'sku'), name='unique_discount_sku')],
            },
        ),
    ]
