# Generated by Django 5.2.14 on 2026-06-28 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_session_uuid',
            field=models.UUIDField(db_index=True, null=True),
        ),
    ]
