# Generated by Django 5.2.14 on 2026-06-26 22:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crop_zoning', '0001_initial'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'farm_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('light', models.CharField(blank=True, default='', help_text='نور مورد نیاز', max_length=255)),
                ('watering', models.CharField(blank=True, default='', help_text='آبیاری', max_length=255)),
                ('soil', models.CharField(blank=True, default='', help_text='خاک مناسب', max_length=255)),
                ('temperature', models.CharField(blank=True, default='', help_text='دمای مناسب', max_length=255)),
                ('growth_stage', models.CharField(blank=True, default='', help_text='مرحله رشد فعلی', max_length=255)),
                ('growth_stages', models.JSONField(blank=True, default=list, help_text='فهرست مراحل رشد محصول')),
                ('icon', models.CharField(blank=True, default='', help_text='آیکون محصول برای فرانت', max_length=100)),
                ('planting_season', models.CharField(blank=True, default='', help_text='فصل کاشت', max_length=255)),
                ('harvest_time', models.CharField(blank=True, default='', help_text='زمان برداشت', max_length=255)),
                ('spacing', models.CharField(blank=True, default='', help_text='فاصله کاشت', max_length=255)),
                ('fertilizer', models.CharField(blank=True, default='', help_text='کود مناسب', max_length=255)),
                ('health_profile', models.JSONField(blank=True, default=dict, help_text='پروفایل سلامت محصول برای KPIها. ساختار نمونه: {"moisture": {"ideal_value": 65, "min_range": 45, "max_range": 75, "weight": 0.4}}')),
                ('irrigation_profile', models.JSONField(blank=True, default=dict, help_text='پروفایل آبیاری محصول برای محاسبات ETc. {"kc_initial": 0.6, "kc_mid": 1.15, "kc_end": 0.8, "growth_stage_duration": {"initial": 20, "mid": 30, "late": 25}}')),
                ('growth_profile', models.JSONField(blank=True, default=dict, help_text='پروفایل رشد محصول برای مدل GDD. {"base_temperature": 10, "required_gdd_for_maturity": 1200, "stage_thresholds": {"flowering": 500, "fruiting": 850}, "current_cumulative_gdd": 320}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='farm_hub.farmtype')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FarmHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('irrigation_method_id', models.IntegerField(blank=True, null=True)),
                ('irrigation_method_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_crop_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_farms', to='crop_zoning.croparea')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_hubs', to=settings.AUTH_USER_MODEL)),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='farms', to='subscriptions.subscriptionplan')),
                ('farm_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farms', to='farm_hub.farmtype')),
                ('products', models.ManyToManyField(blank=True, related_name='farms', to='farm_hub.product')),
            ],
            options={
                'db_table': 'farm_hubs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('farm_type', 'name'), name='unique_product_per_farm_type'),
        ),
    ]
