# Generated by Django 5.2.14 on 2026-07-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmhub',
            name='subscription_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
