# Generated by Django 5.2.12 on 2026-03-20 00:30

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device_hub", "0001_initial"),
        ("farm_hub", "0002_seed_default_catalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmsensor",
            name="physical_device_uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name="farmsensor",
            name="sensor_catalog",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="farm_sensors",
                to="device_hub.sensorcatalog",
            ),
        ),
    ]
