# Generated by Django 5.2.12 on 2026-03-20 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crop_zoning", "0004_croparea_farm"),
        ("farm_hub", "0003_farmsensor_catalog_and_physical_device"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farmhub",
            name="customization",
        ),
        migrations.RemoveField(
            model_name="farmsensor",
            name="customization",
        ),
        migrations.AddField(
            model_name="farmhub",
            name="current_crop_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_for_farms",
                to="crop_zoning.croparea",
            ),
        ),
    ]
