# Generated by Django 5.2.12 on 2026-04-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farm_hub", "0006_seed_expanded_product_catalog"),
        ("access_control", "0002_link_subscription_plan_to_farm"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmhub",
            name="subscription_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="farms",
                to="access_control.subscriptionplan",
            ),
        ),
    ]
