# Generated by Django 5.2.14 on 2026-06-19 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_hub', '0010_move_farmsensor_to_device_hub'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmhub',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='farms', to='subscriptions.subscriptionplan'),
        ),
    ]
