# Generated by Django 5.2.14 on 2026-06-26 22:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('geometry', models.JSONField(default=dict)),
                ('points', models.JSONField(default=list)),
                ('center', models.JSONField(default=dict)),
                ('area_sqm', models.FloatField()),
                ('area_hectares', models.FloatField()),
                ('chunk_area_sqm', models.FloatField()),
                ('zone_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crop_areas',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CropProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crop_products',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CropZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('zone_id', models.CharField(max_length=64)),
                ('geometry', models.JSONField(default=dict)),
                ('points', models.JSONField(default=list)),
                ('center', models.JSONField(default=dict)),
                ('area_sqm', models.FloatField()),
                ('area_hectares', models.FloatField()),
                ('sequence', models.PositiveIntegerField()),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('processing_error', models.TextField(blank=True, default='')),
                ('task_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crop_zones',
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CropZoneAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('external_record_id', models.CharField(blank=True, default='', max_length=64)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('depths', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crop_zone_analyses',
                'ordering': ['crop_zone_id'],
            },
        ),
        migrations.CreateModel(
            name='CropZoneCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', models.PositiveIntegerField()),
                ('sequence', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'crop_zone_criteria',
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CropZoneCultivationRiskLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=16)),
                ('color', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'crop_zone_cultivation_risk_layers',
                'ordering': ['crop_zone_id'],
            },
        ),
        migrations.CreateModel(
            name='CropZoneRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_percent', models.PositiveIntegerField()),
                ('water_need', models.CharField(max_length=128)),
                ('estimated_profit', models.CharField(max_length=128)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crop_zone_recommendations',
                'ordering': ['crop_zone_id'],
            },
        ),
        migrations.CreateModel(
            name='CropZoneSoilQualityLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=16)),
                ('score', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'crop_zone_soil_quality_layers',
                'ordering': ['crop_zone_id'],
            },
        ),
        migrations.CreateModel(
            name='CropZoneWaterNeedLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=16)),
                ('value', models.CharField(max_length=128)),
                ('color', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'crop_zone_water_need_layers',
                'ordering': ['crop_zone_id'],
            },
        ),
    ]
