# Generated by Django 5.2.14 on 2026-06-26 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crop_zoning', '0001_initial'),
        ('farm_hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='croparea',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_areas', to='farm_hub.farmhub'),
        ),
        migrations.AddField(
            model_name='cropzone',
            name='crop_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='crop_zoning.croparea'),
        ),
        migrations.AddField(
            model_name='cropzoneanalysis',
            name='crop_zone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='crop_zoning.cropzone'),
        ),
        migrations.AddField(
            model_name='cropzonecultivationrisklayer',
            name='crop_zone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cultivation_risk_layer', to='crop_zoning.cropzone'),
        ),
        migrations.AddField(
            model_name='cropzonerecommendation',
            name='crop_zone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='crop_zoning.cropzone'),
        ),
        migrations.AddField(
            model_name='cropzonerecommendation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zone_recommendations', to='crop_zoning.cropproduct'),
        ),
        migrations.AddField(
            model_name='cropzonecriteria',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='crop_zoning.cropzonerecommendation'),
        ),
        migrations.AddField(
            model_name='cropzonesoilqualitylayer',
            name='crop_zone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soil_quality_layer', to='crop_zoning.cropzone'),
        ),
        migrations.AddField(
            model_name='cropzonewaterneedlayer',
            name='crop_zone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='water_need_layer', to='crop_zoning.cropzone'),
        ),
        migrations.AddConstraint(
            model_name='cropzone',
            constraint=models.UniqueConstraint(fields=('crop_area', 'zone_id'), name='unique_crop_area_zone_id'),
        ),
    ]
