# Generated by Django 5.2.14 on 2026-06-26 22:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm_hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sensor', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=64)),
                ('expected', models.CharField(max_length=64)),
                ('deviation', models.CharField(max_length=64)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='warning', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='farm_hub.farmhub')),
            ],
            options={
                'db_table': 'farm_anomaly_detections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('external_alert_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('color', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', max_length=32)),
                ('suggested_action', models.TextField(blank=True, default='')),
                ('source_metric_type', models.CharField(blank=True, default='', max_length=255)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('raw_alert', models.JSONField(blank=True, default=dict)),
                ('avatar_icon', models.CharField(blank=True, default='', max_length=64)),
                ('avatar_color', models.CharField(blank=True, default='', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farm_alerts', to='farm_hub.farmhub')),
            ],
            options={
                'db_table': 'farm_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmAlertTrackerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(default='farm_alerts', max_length=64)),
                ('tracker', models.JSONField(blank=True, default=dict)),
                ('headline', models.CharField(blank=True, default='', max_length=255)),
                ('overview', models.TextField(blank=True, default='')),
                ('status_level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', max_length=32)),
                ('raw_llm_response', models.TextField(blank=True, default='')),
                ('structured_context', models.JSONField(blank=True, default=dict)),
                ('last_ai_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_source_update_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_tracker_snapshot', to='farm_hub.farmhub')),
            ],
            options={
                'db_table': 'farm_alert_tracker_snapshots',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True, default='')),
                ('avatar_icon', models.CharField(blank=True, default='', max_length=64)),
                ('avatar_color', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='farm_hub.farmhub')),
            ],
            options={
                'db_table': 'farm_recommendations',
                'ordering': ['-created_at'],
            },
        ),
    ]
