# Generated by Django 5.1.15 on 2026-04-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalydetection',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='warning', max_length=32),
        ),
        migrations.AlterField(
            model_name='farmalert',
            name='color',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', max_length=32),
        ),
    ]
