# Generated by Django 5.1.15 on 2026-04-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm_alerts", "0002_alter_anomalydetection_severity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmalert",
            name="external_alert_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="farmalert",
            name="occurred_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="farmalert",
            name="payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="farmalert",
            name="raw_alert",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="farmalert",
            name="source_metric_type",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="farmalert",
            name="suggested_action",
            field=models.TextField(blank=True, default=""),
        ),
    ]
