# Generated by Django 5.2.14 on 2026-06-26 22:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm_hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerCalendarTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_tags', to='farm_hub.farmhub')),
            ],
            options={
                'db_table': 'farmer_calendar_tags',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='FarmerCalendarZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_zones', to='farm_hub.farmhub')),
            ],
            options={
                'db_table': 'farmer_calendar_zones',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='FarmerCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('deadline', models.BigIntegerField(blank=True, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, choices=[('زیاد', 'High'), ('متوسط', 'Medium'), ('کم', 'Low')], max_length=16, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done')], default='open', max_length=16)),
                ('extended_props', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='farm_hub.farmhub')),
                ('tags', models.ManyToManyField(blank=True, related_name='events', to='farmer_calendar.farmercalendartag')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='farmer_calendar.farmercalendarzone')),
            ],
            options={
                'db_table': 'farmer_calendar_events',
                'ordering': ['scheduled_date', 'start', 'time', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='farmercalendartag',
            constraint=models.UniqueConstraint(fields=('farm', 'value'), name='uniq_farmer_calendar_tag_per_farm'),
        ),
        migrations.AddConstraint(
            model_name='farmercalendarzone',
            constraint=models.UniqueConstraint(fields=('farm', 'value'), name='uniq_farmer_calendar_zone_per_farm'),
        ),
    ]
