# Generated by Django 5.2.14 on 2026-07-03 20:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('cart', '0002_initial'),
        ('farm_hub', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('assigned_team', models.CharField(blank=True, max_length=100, null=True)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('installer_notes', models.TextField(blank=True, null=True)),
                ('cart_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='installation_requests', to='cart.cartitem')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farm_hub.farmhub')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('carrier', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('backordered', 'Backordered'), ('preparing', 'Preparing'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='preparing', max_length=50)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='address.address')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('allocated_device_serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('cart_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_items', to='cart.cartitem')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_items', to='fullfilment.shipment')),
            ],
        ),
    ]
