# Generated by Django 5.2.14 on 2026-07-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullfilment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationrequest',
            name='cart_item',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='cart_item',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
