# Generated by Django 5.2.14 on 2026-07-03 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('fullfilment', '0002_alter_installationrequest_cart_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationrequest',
            name='farm_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installation_request', to='address.address'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='shipping_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_item', to='address.address'),
        ),
    ]
