# Generated by Django 5.1.15 on 2026-04-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmdashboardconfig',
            name='row_order',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
