# Generated by Django 5.2.14 on 2026-06-24 21:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('cart', '0001_initial'),
        ('farm_hub', '0011_alter_farmhub_subscription_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_requirements', 'Awaiting_requirements'), ('awaiting_payment', 'Awaiting_payment'), ('payment_processing', 'payment_processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', max_length=30)),
                ('pricing_snapshot', models.JSONField(blank=True, default=dict)),
                ('shipping_address_snapshot', models.JSONField(blank=True, default=dict)),
                ('farm_address_snapshot', models.JSONField(blank=True, default=dict)),
                ('billing_address_snapshot', models.JSONField(blank=True, default=dict)),
                ('customer_notes', models.TextField(blank=True, null=True)),
                ('payment_deadline_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='address.address')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_sessions', to='cart.cart')),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_sessions', to='farm_hub.farmhub')),
                ('farm_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='address.address')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='address.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
