# Generated by Django 5.2.14 on 2026-06-26 22:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_uuid', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_requirements', 'Awaiting_requirements'), ('awaiting_payment', 'Awaiting_payment'), ('payment_processing', 'payment_processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', max_length=30)),
                ('total_amount', models.PositiveIntegerField(verbose_name='total_order_amount')),
                ('shipping_address_snapshot', models.JSONField(blank=True, default=dict)),
                ('farm_address_snapshot', models.JSONField(blank=True, default=dict)),
                ('items_snapshot', models.JSONField(blank=True, null=True)),
                ('payment_deadline_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
