# Generated by Django 5.2.14 on 2026-06-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutsession',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_payment', 'Awaiting_payment'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', max_length=30),
        ),
    ]
