# Generated by Django 5.1.15 on 2026-04-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SensorExternalRequestLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("farm_uuid", models.UUIDField(db_index=True)),
                ("sensor_catalog_uuid", models.UUIDField(blank=True, db_index=True, null=True)),
                ("physical_device_uuid", models.UUIDField(db_index=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "sensor_external_request_logs",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
