# Generated by Django 5.2.12 on 2026-03-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='نام گیاه', max_length=255, unique=True)),
                ('light', models.CharField(blank=True, help_text='نور مورد نیاز', max_length=255)),
                ('watering', models.CharField(blank=True, help_text='آبیاری', max_length=255)),
                ('soil', models.CharField(blank=True, help_text='خاک مناسب', max_length=255)),
                ('temperature', models.CharField(blank=True, help_text='دمای مناسب', max_length=255)),
                ('planting_season', models.CharField(blank=True, help_text='فصل کاشت', max_length=255)),
                ('harvest_time', models.CharField(blank=True, help_text='زمان برداشت', max_length=255)),
                ('spacing', models.CharField(blank=True, help_text='فاصله کاشت', max_length=255)),
                ('fertilizer', models.CharField(blank=True, help_text='کود مناسب', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'گیاه',
                'verbose_name_plural': 'گیاهان',
                'ordering': ['name'],
            },
        ),
    ]
