from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/docs/swagger/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path(
        "api/docs/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"
    ),
    path("api/auth/", include("auth.urls")),
    path("api/account/", include("account.urls")),
    path("api/farm-hub/", include("farm_hub.urls")),
    path("api/access-control/", include("access_control.urls")),
    path("api/device-hub/", include("device_hub.urls")),
    path("api/sensor-catalog/", include("device_hub.sensor_catalog_urls")),
    path("api/farm-dashboard-config/", include("dashboard.urls_config")),
    path("api/farm-dashboard/", include("dashboard.urls")),
    path("api/crop-health/", include("crop_health.urls")),
    path("api/soil/", include("soil.urls")),
    path("api/location-data/", include("crop_zoning.urls")),
    # path("api/yield-harvest/", include("yield_harvest.urls")),
    path("api/yield-harvest/", include("yield_harvest.crop_simulation_urls")),
    path("api/pest-detection/", include("pest_detection.urls")),
    path("api/pest-disease/", include("pest_detection.pest_disease_urls")),
    path("api/irrigation/", include("irrigation.urls")),
    path("api/weather/", include("water.weather_urls")),
    path("api/water/", include("water.urls")),
    path("api/economy/", include("economic_overview.urls")),
    path("api/fertilization/", include("fertilization.urls")),
    path("api/farm-ai-assistant/", include("farm_ai_assistant.urls")),
    path("api/notifications/", include("notifications.urls")),
    path("api/farm-alerts/", include("farm_alerts.urls")),
    path("api/plants/", include("plants.urls")),
    path("api/events/", include("farmer_calendar.urls")),
    path("api/farmer-todos/", include("farmer_todos.urls")),
    path("api/sensor-external-api/", include("device_hub.sensor_external_api_urls")),
    path("api/address/", include("address.urls")),
    path("api/commerce-catalog/", include("commerce_catalog.urls")),
    path("api/pricing/", include("pricing.urls")),
    path("api/wallet/", include("wallet.urls")),
    path("api/ledger/", include("ledger.urls")),
    path("api/cart/", include("cart.urls")),
    path("api/checkout/", include("checkout.urls")),
    path("api/order/", include("order.urls")),
]
