# Generated by Django 5.2.14 on 2026-06-26 22:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending', 'Pending')], default='active', max_length=20)),
                ('available_balance', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('held_balance', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('pending_settlements', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('total_balance', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallets', to='pricing.currency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('authority', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('transaction_type', models.CharField(choices=[('topup', 'Topup'), ('order_payment', 'Order Payment'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('settlement', 'Settlement'), ('withdrawal', 'Withdrawal'), ('cashback', 'Cashback')], max_length=20)),
                ('direction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=20)),
                ('status_type', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('reversed', 'Reversed')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('reference_type', models.CharField(blank=True, help_text='نوع موجودیت مثل Order, PaymentIntent', max_length=255, null=True)),
                ('reference_id', models.CharField(blank=True, help_text='شناسه موجودیت متصل', max_length=100, null=True)),
                ('method', models.CharField(blank=True, help_text='مثلا درگاه زرین\u200cپال یا انتقال پایا', max_length=100, null=True)),
                ('balance_after', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('reason_code', models.CharField(blank=True, help_text='کد دلیل برای اصلاحیه\u200cهای دستی', max_length=50, null=True)),
                ('operator_note', models.TextField(blank=True, help_text='یادداشت ادمین', null=True)),
                ('actor_id', models.IntegerField(blank=True, help_text='آی\u200cدی ادمینی که این تراکنش را ثبت کرده', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=18)),
                ('shiba_number', models.CharField(max_length=26)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('account_holder_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('bank_tracking_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_detail', to='wallet.transaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_requests', to='wallet.wallet')),
            ],
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference_type', 'reference_id'], name='wallet_tran_referen_4c93e3_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='wallet_tran_created_fb97c1_idx'),
        ),
    ]
