# Generated by Django 5.2.14 on 2026-06-20 10:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending', 'Pending')], default='active', max_length=20),
        ),
    ]
