# Generated by Django 5.2.14 on 2026-06-20 10:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_transaction_balance_after_alter_wallet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18),
        ),
    ]
