# Generated by Django 5.2.14 on 2026-06-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='authority',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
