# Generated by Django 5.2.14 on 2026-05-16 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=51)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_multiple', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=51)),
                ('bundle_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('subscription_plan', 'Subscription Plan'), ('physical_device', 'Physical Device'), ('physical_supply', 'Physical Supply'), ('service', 'Service'), ('installation_service', 'Installation Service'), ('farm_analysis', 'Farm Analysis'), ('credit_topup', 'Credit Topup')], default='physical_supply', max_length=32)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_installable', models.BooleanField(default=False)),
                ('requires_farm_context', models.BooleanField(default=False)),
                ('external_source', models.CharField(blank=True, max_length=50, null=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=51)),
                ('code', models.CharField(max_length=150, unique=True)),
                ('rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant', to='commerce_catalog.sellableitem')),
            ],
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150, unique=True)),
                ('title', models.CharField(blank=True, max_length=51)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku', to='commerce_catalog.sellableitem')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_item', to='commerce_catalog.productbundle')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_item', to='commerce_catalog.sku')),
            ],
        ),
        migrations.AddField(
            model_name='sellableitem',
            name='tax_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sellable_item', to='commerce_catalog.taxclass'),
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=60)),
                ('display_order', models.PositiveIntegerField()),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_value', to='commerce_catalog.productvariant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('variant',), name='only_one_attribute_can_be_the_main_selected'), models.UniqueConstraint(fields=('variant', 'value'), name='unique_value_per_variant')],
            },
        ),
        migrations.CreateModel(
            name='AddOnAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False)),
                ('add_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_assignments', to='commerce_catalog.productaddon')),
                ('sellable_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_assignments', to='commerce_catalog.sellableitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sellable_item', 'add_on'), name='unique_addon_per_item')],
            },
        ),
        migrations.AddConstraint(
            model_name='sku',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('item',), name='unique_default_sku_per_item'),
        ),
        migrations.AddConstraint(
            model_name='productbundleitem',
            constraint=models.UniqueConstraint(fields=('bundle', 'sku'), name='unique_bundle_sku'),
        ),
        migrations.AddConstraint(
            model_name='sellableitem',
            constraint=models.UniqueConstraint(fields=('external_source', 'external_id'), name='unique_external_product'),
        ),
    ]
