# Generated by Django 5.2.14 on 2026-06-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellableitem',
            old_name='requires_farm_context',
            new_name='requires_farm_address',
        ),
        migrations.AddField(
            model_name='sellableitem',
            name='requires_shipping_address',
            field=models.BooleanField(default=False),
        ),
    ]
