# Generated by Django 5.2.14 on 2026-07-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellableitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sku',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
