# Generated by Django 5.2.14 on 2026-07-04 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_catalog', '0002_alter_sellableitem_image_alter_sku_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributevalue',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='commerce_catalog.productvariant'),
        ),
        migrations.AlterField(
            model_name='productbundleitem',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_items', to='commerce_catalog.productbundle'),
        ),
        migrations.AlterField(
            model_name='productbundleitem',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='commerce_catalog.sku'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='commerce_catalog.sellableitem'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='commerce_catalog.sellableitem'),
        ),
    ]
