# Generated by Django 5.2.14 on 2026-07-05 22:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_catalog', '0004_sellableitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellableitem',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
