# Generated by Django 5.2.14 on 2026-06-26 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_id', models.IntegerField(primary_key=True, serialize=False)),
                ('province_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_local_id', models.CharField(blank=True, max_length=3, null=True)),
                ('city_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='address.province')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('shipping', 'Shipping'), ('billing', 'Billing'), ('farm_location', 'Farm_location')], default='shipping', max_length=20)),
                ('receiver_name', models.CharField(blank=True, max_length=30, null=True)),
                ('receiver_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('latitute', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longtitute', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('for_sensor', models.BooleanField(blank=True, default=False, null=True)),
                ('postal_code', models.CharField(max_length=15, null=True)),
                ('address_detail', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city', to='address.city')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='province', to='address.province')),
            ],
        ),
    ]
