# Generated by Django 5.2.14 on 2026-06-26 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0001_initial'),
        ('device_hub', '0001_initial'),
        ('farm_hub', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrule',
            name='farm_types',
            field=models.ManyToManyField(blank=True, related_name='access_rules', to='farm_hub.farmtype'),
        ),
        migrations.AddField(
            model_name='accessrule',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='rules', to='access_control.accessfeature'),
        ),
        migrations.AddField(
            model_name='accessrule',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='access_rules', to='farm_hub.product'),
        ),
        migrations.AddField(
            model_name='accessrule',
            name='sensor_catalogs',
            field=models.ManyToManyField(blank=True, related_name='access_rules', to='device_hub.devicecatalog'),
        ),
        migrations.AddField(
            model_name='accessrule',
            name='subscription_plans',
            field=models.ManyToManyField(blank=True, related_name='access_rules', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='farmaccessprofile',
            name='farm',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_profile', to='farm_hub.farmhub'),
        ),
        migrations.AddField(
            model_name='farmaccessprofile',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farm_access_profiles', to='subscriptions.subscriptionplan'),
        ),
    ]
