# Generated by Django 5.2.12 on 2026-03-19 16:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("access_control", "0001_initial"),
        ("farm_hub", "0006_seed_expanded_product_catalog"),
    ]

    operations = []
