# Generated by Django 5.2.12 on 2026-04-03

from django.db import migrations


def seed_default_access_rules(apps, schema_editor):
    AccessFeature = apps.get_model("access_control", "AccessFeature")
    AccessRule = apps.get_model("access_control", "AccessRule")
    SubscriptionPlan = apps.get_model("access_control", "SubscriptionPlan")
    SensorCatalog = apps.get_model("sensor_catalog", "SensorCatalog")

    from access_control.catalog import DEFAULT_ACCESS_FEATURES, DEFAULT_ACCESS_RULES, DEFAULT_SUBSCRIPTION_PLANS

    features_by_code = {}
    for feature_data in DEFAULT_ACCESS_FEATURES:
        feature, _created = AccessFeature.objects.update_or_create(
            code=feature_data["code"],
            defaults={
                "name": feature_data["name"],
                "feature_type": feature_data["feature_type"],
                "description": feature_data.get("description", ""),
                "metadata": feature_data.get("metadata", {}),
                "default_enabled": feature_data.get("default_enabled", False),
            },
        )
        features_by_code[feature.code] = feature

    plans_by_code = {}
    for plan_data in DEFAULT_SUBSCRIPTION_PLANS:
        plan, _created = SubscriptionPlan.objects.update_or_create(
            code=plan_data["code"],
            defaults={
                "name": plan_data["name"],
                "description": plan_data.get("description", ""),
                "metadata": plan_data.get("metadata", {}),
                "is_active": True,
            },
        )
        plans_by_code[plan.code] = plan

    sensor_catalogs_by_name = {
        sensor.name: sensor for sensor in SensorCatalog.objects.filter(name__in=_sensor_names(DEFAULT_ACCESS_RULES))
    }

    for rule_data in DEFAULT_ACCESS_RULES:
        rule, _created = AccessRule.objects.update_or_create(
            code=rule_data["code"],
            defaults={
                "name": rule_data["name"],
                "description": rule_data.get("description", ""),
                "effect": rule_data.get("effect", "allow"),
                "priority": rule_data.get("priority", 100),
                "metadata": rule_data.get("metadata", {}),
                "is_active": True,
            },
        )
        rule.features.set([features_by_code[code] for code in rule_data.get("features", []) if code in features_by_code])
        rule.subscription_plans.set(
            [plans_by_code[code] for code in rule_data.get("subscription_plans", []) if code in plans_by_code]
        )
        rule.sensor_catalogs.set(
            [sensor_catalogs_by_name[name] for name in rule_data.get("sensor_catalogs", []) if name in sensor_catalogs_by_name]
        )


def unseed_default_access_rules(apps, schema_editor):
    AccessFeature = apps.get_model("access_control", "AccessFeature")
    AccessRule = apps.get_model("access_control", "AccessRule")
    SubscriptionPlan = apps.get_model("access_control", "SubscriptionPlan")

    from access_control.catalog import DEFAULT_ACCESS_FEATURES, DEFAULT_ACCESS_RULES, DEFAULT_SUBSCRIPTION_PLANS

    AccessRule.objects.filter(code__in=[item["code"] for item in DEFAULT_ACCESS_RULES]).delete()
    AccessFeature.objects.filter(code__in=[item["code"] for item in DEFAULT_ACCESS_FEATURES]).delete()
    SubscriptionPlan.objects.filter(code__in=[item["code"] for item in DEFAULT_SUBSCRIPTION_PLANS]).delete()


def _sensor_names(rule_data_list):
    names = []
    for rule_data in rule_data_list:
        names.extend(rule_data.get("sensor_catalogs", []))
    return names


class Migration(migrations.Migration):
    dependencies = [
        ("access_control", "0002_link_subscription_plan_to_farm"),
        ("sensor_catalog", "0002_sensorcatalog_supported_power_sources"),
    ]

    operations = [
        migrations.RunPython(seed_default_access_rules, unseed_default_access_rules),
    ]
