# Generated by Django 5.2.14 on 2026-06-19 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0005_backfill_farm_subscription_plans'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmaccessprofile',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farm_access_profiles', to='subscriptions.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='accessrule',
            name='subscription_plans',
            field=models.ManyToManyField(blank=True, related_name='access_rules', to='subscriptions.subscriptionplan'),
        ),
    ]
