# Generated by Django 5.2.14 on 2026-06-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0006_alter_farmaccessprofile_subscription_plan_and_more'),
        ('farm_hub', '0011_alter_farmhub_subscription_plan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
