# Generated by Django 5.2.14 on 2026-07-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, default=30, help_text='Duration of the subscription plan in days', null=True),
        ),
    ]
