# Generated by Django 5.2.14 on 2026-06-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_hub', '0010_farmdevice_cluster_context_and_log_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmdevice',
            name='customization',
        ),
    ]
