# Generated by Django 5.2.12 on 2026-03-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sensor_catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensorcatalog",
            name="supported_power_sources",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
