# Generated by Django 5.1.15 on 2026-04-25 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_catalog', '0003_sensorcatalog_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensorcatalog',
            options={'ordering': ['code']},
        ),
    ]
