# Generated by Django 5.2.14 on 2026-06-26 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('commerce_catalog', '0001_initial'),
        ('farm_hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='farm_hub.farmhub'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='commerce_catalog.sku'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'sku', 'farm'), name='unique_record_per_cart_sku_farm_fields'),
        ),
    ]
