# Generated by Django 5.2.14 on 2026-06-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_todos', '0002_merge_todos_into_calendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmertodotask',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='farmertodotask',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='farmertodotask',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='farmertodozone',
            name='farm',
        ),
        migrations.DeleteModel(
            name='FarmerTodoTag',
        ),
        migrations.DeleteModel(
            name='FarmerTodoTask',
        ),
        migrations.DeleteModel(
            name='FarmerTodoZone',
        ),
    ]
