# Generated by Django 5.1.7 on 2025-02-20 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("farm_hub", "0006_seed_expanded_product_catalog"),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("level", models.CharField(default="info", max_length=32)),
                ("is_read", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="farm_hub.farmhub",
                    ),
                ),
            ],
            options={
                "db_table": "farm_notifications",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
