# Generated by Django 5.2.14 on 2026-06-26 22:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm_hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('level', models.CharField(default='info', max_length=32)),
                ('endpoint', models.CharField(blank=True, default='', max_length=64)),
                ('suggested_action', models.TextField(blank=True, default='')),
                ('source_alert_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('source_metric_type', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='farm_hub.farmhub')),
            ],
            options={
                'db_table': 'farm_notifications',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
