# Generated by Django 5.2.14 on 2026-06-26 22:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('cart', '0001_initial'),
        ('farm_hub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='order_status')),
                ('pricing_snapshot', models.JSONField(blank=True, default=dict)),
                ('shipping_address_snapshot', models.JSONField(blank=True, default=dict)),
                ('farm_address_snapshot', models.JSONField(blank=True, default=dict)),
                ('billing_address_snapshot', models.JSONField(blank=True, default=dict)),
                ('items_snapshot', models.JSONField(blank=True, null=True)),
                ('customer_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='address.address')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_sessions', to='cart.cart')),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_sessions', to='farm_hub.farmhub')),
                ('farm_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='address.address')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='address.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
