# Generated by Django 5.2.14 on 2026-06-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=6, max_digits=18, null=True),
        ),
    ]
