# Generated by Django 5.2.14 on 2026-06-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address_snapshot',
        ),
        migrations.AddField(
            model_name='order',
            name='farm_address_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
