name: Docker Compose CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
 
    - name: Checkout code
      uses: actions/checkout@v4

  
    - name: Build and Run Docker Compose
      run: |
        docker compose -f docker-compose-original-source.yml up -d --build

  
    - name: Wait for Database
      run: sleep 10

  
    - name: Run Django Tests inside Docker
      run: |
        docker compose exec -T web python manage.py test


    - name: Clean up Docker
      if: always() 
      run: |
        docker compose -f docker-compose-original-source.yml down

